#!/bin/sh
### BEGIN INIT INFO
# Provides:         	touchd
# Required-Start:	$local_fs
# Required-Stop:	$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	driver for some touch displays
### END INIT INFO

